io.lettuce.core.RedisCommandExecutionException: NOAUTH Authentication required on CLIENT and READONLY command
Using custom credentials provider can delay providing of credentials. In this case applyPostHandshake and applyConnectionMetadata got executed before handshake and lead to NOAUTH error in the log for CLIENT command.