Guard PauseDetectorWrapper initialization against absence of LatencyUtils #520
LatencyUtils is an optional dependency that is allowed to be absent. A previous change introduced a static initialization path to load PauseDetector, a type from LatencyUtils which caused DefaultCommandLatencyCollector initialization to fail.

Lettuce now encapsulates PauseDetector in a lazy-loading wrapper without defining PauseDetector on the wrapper type but a subtype to prevent NoClassDefFoundError if LatencyUtils is absent.